```
Upgraded from  3.4.2-65 to 3.15.6-10.6.342
apiur.exe


Generate robot program doesn't work with Python https://robodk.com/forum/Thread-Generate-robot-program-doesn-t-work-with-Python




robolink check_status()

File "C:\RoboDK\Python\robodk\robolink.py", line 1014, in _moveX
self._check_status() #will wait here


```
